### ISSUE TITLE
Check fails on a valid PR from a fork

### ISSUE THREAD

**Issue by mhoffm-aiven** [empathictech/versioning-checker#6]
Hey @mwcodebase,

i'm currently using your action here: https://github.com/aiven/terraform-provider-aiven/blob/master/.github/workflows/changelog-checker.yml. In my setup the action seems to fail on valid PRs when they stem from a fork ( for example https://github.com/aiven/terraform-provider-aiven/runs/4208588078?check_suite_focus=true this run ). 

Is there something i did wrong in my setup?

Thanks!

**Comment by mwcodebase** [comment]
Hey! Thanks for pointing this out, at first glance it looks like the issue's on my end not yours. I will try and find some time this weekend to add fork PR support.

**Comment by mhoffm-aiven** [comment]
Thanks for looking into it!

**Comment by mwcodebase** [comment]
Hey! Apologies for the wait, but I think I've got it sorted - before I do the official release though can you try v2.3-test with the new optional param?

Example: https://github.com/mwcodebase/versioning-checker/blob/v2.3/.github/workflows/main.yml#L21

**Comment by mwcodebase** [comment]
Hey @mhoffm-aiven did you get a chance to test out the new version?

**Comment by mhoffm-aiven** [comment]
Hey @mwcodebase !

sorry i was busy and forgot, i have a little time on my hands this week, ill test it tomorrow!

**Comment by mwcodebase** [comment]
Yup! For whatever reason that info is missing from the PR data that gets sent to the action
